version: '3'

services:
  app:
    container_name: express-apollo-server_default
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'      