version: '3'

services:
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'      