version: '3'

services:
  app:
    container_name: express-apollo-server_default
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'      
volumes:
  mongodb_data:
    driver: local      